using HattrickAI.CHPP;
using System.Globalization;
using System.Xml.Linq;
namespace HattrickAI.V4.Core;
public sealed record V4Player(int Id,string Name,int Keeper,int Defending,int Playmaking,int Passing,int Winger,int Scoring,int Stamina,int Form,int Experience);
public sealed record V4Slot(string Code,string Position,string Name,int PlayerId,double X,double Y,string Reason,double Rating);
public sealed record V4Pitch(string TeamName,string Formation,IReadOnlyList<V4Slot> Players,bool Opponent);
public sealed record V4AnalysisResult(V4Pitch OpponentPitch,V4Pitch OwnPitch,string MatchTitle,DateTimeOffset GeneratedAt);
public sealed class V4AnalysisService
{
 private readonly ChppOAuthClient _oauth; public V4AnalysisService(ChppOAuthClient oauth)=>_oauth=oauth;
 public async Task<V4AnalysisResult> RunAsync(CancellationToken ct=default)
 {
  var ownTeam=await ReadTeamAsync(ct); var ownPlayers=await ReadPlayersAsync(ownTeam.TeamId,ct);
  var matches=ParseMatches(await _oauth.GetXmlAsync("matches",new Dictionary<string,string?> { ["version"]="1.3",["teamId"]=$"{ownTeam.TeamId}" },ct),ownTeam.TeamId);
  var next=matches.Where(x=>x.Date>DateTimeOffset.UtcNow).OrderBy(x=>x.Date).FirstOrDefault(); if(next.MatchId<=0)throw new InvalidOperationException("Yaklaşan maç bulunamadı.");
  var oppId=next.HomeTeamId==ownTeam.TeamId?next.AwayTeamId:next.HomeTeamId; var oppName=next.HomeTeamId==ownTeam.TeamId?next.AwayName:next.HomeName; if(oppId<=0)throw new InvalidOperationException("Rakip takım ID'si bulunamadı.");
  var oppMatches=ParseMatches(await _oauth.GetXmlAsync("matches",new Dictionary<string,string?> { ["version"]="1.3",["teamId"]=$"{oppId}" },ct),oppId);
  var last=oppMatches.Where(x=>x.Date<DateTimeOffset.UtcNow).OrderByDescending(x=>x.Date).FirstOrDefault(); if(last.MatchId<=0)throw new InvalidOperationException("Rakibin son maçı bulunamadı.");
  var lineup=ParseLineup(await _oauth.GetXmlAsync("matchlineup",new Dictionary<string,string?> { ["version"]="1.1",["matchID"]=$"{last.MatchId}",["teamID"]=$"{oppId}" },ct));
  var oppPlayers=await ReadPlayersAsync(oppId,ct); var byId=oppPlayers.ToDictionary(x=>x.Id);
  var mapped=lineup.Where(x=>byId.ContainsKey(x.PlayerId)).Select(x=>x with{Rating=Math.Round(PositionRating(byId[x.PlayerId],x.Code),2)}).ToList();
  if(mapped.Count<11)throw new InvalidOperationException("Rakip son maç kadrosundaki 11 oyuncunun tamamı CHPP oyuncu verisiyle eşleşmedi.");
  var own=BuildOwnPitch(ownTeam.TeamName,ownPlayers); var opp=new V4Pitch(oppName,"Son maç • "+FormationFromSlots(mapped),mapped,true);
  var title=$"{next.Date:dd.MM.yyyy HH:mm} • {oppName} • {(next.HomeTeamId==ownTeam.TeamId?"Ev":"Deplasman")}";
  return new V4AnalysisResult(opp,own,title,DateTimeOffset.UtcNow);
 }
 private async Task<(int TeamId,string TeamName)> ReadTeamAsync(CancellationToken ct){var x=await _oauth.GetXmlAsync("teamdetails",new Dictionary<string,string?> { ["version"]="3.0" },ct);var t=XDocument.Parse(x).Descendants("Team").FirstOrDefault();var id=ReadInt(t,"TeamID");if(id<=0)throw new InvalidOperationException("Takım bilgisi alınamadı.");return(id,ReadText(t,"TeamName")??"Takım");}
 private async Task<IReadOnlyList<V4Player>> ReadPlayersAsync(int teamId,CancellationToken ct){var x=await _oauth.GetXmlAsync("players",new Dictionary<string,string?> { ["version"]="1.3",["teamId"]=$"{teamId}" },ct);return XDocument.Parse(x).Descendants("Player").Select(p=>new V4Player(ReadInt(p,"PlayerID"),ReadText(p,"PlayerName")??"Oyuncu",ReadInt(p,"KeeperSkill"),ReadInt(p,"DefenderSkill"),ReadInt(p,"PlaymakerSkill"),ReadInt(p,"PassingSkill"),ReadInt(p,"WingerSkill"),ReadInt(p,"ScorerSkill"),ReadInt(p,"StaminaSkill"),ReadInt(p,"PlayerForm"),ReadInt(p,"Experience"))).Where(p=>p.Id>0).ToList();}
 private static List<(int MatchId,DateTimeOffset Date,int HomeTeamId,int AwayTeamId,string HomeName,string AwayName)> ParseMatches(string xml,int teamId){var r=new List<(int,DateTimeOffset,int,int,string,string)>();foreach(var m in XDocument.Parse(xml).Descendants("Match")){var id=ReadInt(m,"MatchID");var d=ReadDate(m,"MatchDate");var h=ReadInt(m,"HomeTeamID");var a=ReadInt(m,"AwayTeamID");if(id>0&&d!=default&&(h==teamId||a==teamId))r.Add((id,d,h,a,ReadText(m,"HomeTeamName")??"Ev sahibi",ReadText(m,"AwayTeamName")??"Deplasman"));}return r;}
 private static List<V4Slot> ParseLineup(string xml){var r=new List<V4Slot>();foreach(var p in XDocument.Parse(xml).Descendants("Player").Take(11)){var pos=ReadInt(p,"PositionCode");var q=pos switch{1=>("GK","Kaleci",50d,10d),2=>("DEF-R","Sağ bek",88d,34d),3=>("DEF-CR","Sağ stoper",70d,36d),4=>("DEF-CL","Sol stoper",30d,36d),5=>("DEF-L","Sol bek",12d,34d),6=>("W-R","Sağ kanat",88d,50d),7=>("IM-R","Sağ iç",66d,50d),8=>("IM-L","Sol iç",34d,50d),9=>("W-L","Sol kanat",12d,50d),10=>("FW-L","Sol forvet",38d,82d),11=>("FW-R","Sağ forvet",62d,82d),_=>("IM-C","Merkez",50d,50d)};r.Add(new V4Slot(q.Item1,q.Item2,ReadText(p,"PlayerName")??"Oyuncu",ReadInt(p,"PlayerID"),q.Item3,q.Item4,"Rakibin son maçındaki gerçek pozisyonu",0));}return r;}
 private static V4Pitch BuildOwnPitch(string teamName,IReadOnlyList<V4Player> p){var u=new HashSet<int>();V4Player Pick(Func<V4Player,double>s){var x=p.Where(v=>!u.Contains(v.Id)).OrderByDescending(s).FirstOrDefault()??throw new InvalidOperationException("Önerilen 11 oluşturulamadı: yeterli oyuncu verisi yok.");u.Add(x.Id);return x;}var r=new List<V4Slot>();var g=Pick(x=>x.Keeper*2+x.Form*.1);r.Add(Slot("GK","Kaleci",g,50,10,"En yüksek kalecilik"));var dl=Pick(x=>x.Defending+x.Passing*.1);var dcl=Pick(x=>x.Defending+x.Passing*.12+x.Experience*.08);var dcr=Pick(x=>x.Defending+x.Passing*.12+x.Experience*.05);var dr=Pick(x=>x.Defending+x.Passing*.1);r.Add(Slot("DEF-L","Sol bek",dl,12,34,"4'lü savunma dengesi"));r.Add(Slot("DEF-CL","Sol stoper",dcl,30,36,"Merkez savunma gücü"));r.Add(Slot("DEF-CR","Sağ stoper",dcr,70,36,"Merkez savunma gücü"));r.Add(Slot("DEF-R","Sağ bek",dr,88,34,"4'lü savunma dengesi"));var wl=Pick(x=>x.Winger*1.2+x.Passing*.2);var il=Pick(x=>x.Playmaking+x.Passing*.25+x.Stamina*.15);var ir=Pick(x=>x.Playmaking+x.Passing*.25+x.Stamina*.15+x.Experience*.05);var wr=Pick(x=>x.Winger*1.2+x.Passing*.2);r.Add(Slot("W-L","Sol kanat",wl,12,50,"Kanat genişliği"));r.Add(Slot("IM-L","Sol iç",il,34,50,"Orta saha hakimiyeti"));r.Add(Slot("IM-R","Sağ iç",ir,66,50,"Orta saha hakimiyeti"));r.Add(Slot("W-R","Sağ kanat",wr,88,50,"Kanat genişliği"));var fl=Pick(x=>x.Scoring*1.1+x.Passing*.2+x.Winger*.1);var fr=Pick(x=>x.Scoring*1.1+x.Passing*.2+x.Winger*.1+x.Experience*.05);r.Add(Slot("FW-L","Sol forvet",fl,38,82,"Golcülük"));r.Add(Slot("FW-R","Sağ forvet",fr,62,82,"Golcülük ve bağlantı"));return new V4Pitch(teamName,"4-4-2",r,false);}
 private static V4Slot Slot(string c,string pos,V4Player p,double x,double y,string reason)=>new(c,pos,p.Name,p.Id,x,y,reason,Math.Round(PositionRating(p,c),2));
 private static double PositionRating(V4Player p,string c){var raw=c switch{"GK"=>p.Keeper*.75+p.Defending*.15+p.Form*.1,"DEF-L"or"DEF-CL"or"DEF-CR"or"DEF-R"=>p.Defending*.7+p.Passing*.15+p.Playmaking*.1+p.Form*.05,"IM-L"or"IM-C"or"IM-R"=>p.Playmaking*.55+p.Passing*.2+p.Stamina*.15+p.Defending*.1,"W-L"or"W-R"=>p.Winger*.45+p.Playmaking*.2+p.Passing*.2+p.Defending*.1+p.Form*.05,"FW-L"or"FW-R"=>p.Scoring*.55+p.Passing*.2+p.Winger*.15+p.Playmaking*.1,_=>0};return Math.Clamp(raw,0,20);}
 private static string FormationFromSlots(IEnumerable<V4Slot>s){var a=s.ToList();return$"{a.Count(x=>x.Code.StartsWith("DEF"))}-{a.Count(x=>x.Code.StartsWith("W-")||x.Code.StartsWith("IM"))}-{a.Count(x=>x.Code.StartsWith("FW"))}";}
 private static int ReadInt(XElement? n,string k)=>int.TryParse(ReadText(n,k),NumberStyles.Integer,CultureInfo.InvariantCulture,out var v)?v:0;
 private static string? ReadText(XElement? n,string k)=>n?.Element(k)?.Value?.Trim()??n?.Descendants(k).FirstOrDefault()?.Value?.Trim();
 private static DateTimeOffset ReadDate(XElement n,string k)=>DateTimeOffset.TryParse(ReadText(n,k),CultureInfo.InvariantCulture,DateTimeStyles.AssumeUniversal,out var v)?v:default;
}