using System.Text.Json;
using HattrickAI.V5.Core;

namespace HattrickAI.V5.OfflineTests;

public static class FinalPredictionContinuityRegression
{
    public static async Task<int> RunAsync(string path, CancellationToken cancellationToken = default)
    {
        if (!File.Exists(path)) return Fail($"fixture bulunamadı: {path}");
        try
        {
            await using var stream=File.OpenRead(path);using var doc=await JsonDocument.ParseAsync(stream,cancellationToken:cancellationToken);var root=doc.RootElement;var normalized=root.GetProperty("normalized");var analysis=root.GetProperty("v5Analysis");
            var players=normalized.GetProperty("ownPlayers").EnumerateArray().Select(ReadPlayer).ToList();var opponentRating=ReadRating(analysis.GetProperty("opponentRating"));var opponent=new OpponentMatchProfile(GetString(analysis,"opponentName","Opponent"),GetString(analysis,"opponentFormation",""),opponentRating,new OpponentThreatEngine().Analyze(opponentRating));var context=new MatchDataContext(players,0,GetString(analysis.GetProperty("ownLineup"),"teamName","Fixture"),opponent,RatingContext.Default,MatchQuestionnaire.Default);
            Console.WriteLine("=== C17 FINALPREDICTION CONTINUITY REGRESSION ===");var result=await new MotorPipelineService().RunAsync(context,players,cancellationToken,"offline-c17-finalprediction");
            Check(result.FinalPrediction is not null,"FinalPrediction missing");Check(result.M11 is not null&&result.M11.Prediction is not null,"M11 prediction missing");Check(result.M9 is not null,"selected M9 result missing");var final=result.FinalPrediction!;var m11=result.M11!.Prediction!;var m9=result.M9!;var db2=result.CandidateDatabase2;var winnerId=Signature(result.FinalPlan.Lineup);var winner=db2.FirstOrDefault(x=>x.CandidateId==winnerId);
            Check(winner is not null,"FinalPlan winner is absent from DB2");Check(winner!.Prediction is not null,"DB2 winner prediction missing");Check(final==m11,"FinalPrediction is not identical to M11 prediction");Check(final==m9.Prediction,"FinalPrediction is not identical to selected M9 prediction");Check(final==winner.Prediction,"FinalPrediction is not identical to DB2 winner prediction");
            Check(double.IsFinite(final.ExpectedHomeGoals)&&double.IsFinite(final.ExpectedAwayGoals),"FinalPrediction expected goals are not finite");Check(double.IsFinite(final.WinProbability)&&double.IsFinite(final.DrawProbability)&&double.IsFinite(final.LossProbability),"FinalPrediction W/D/L are not finite");Check(final.WinProbability is >=0 and <=1&&final.DrawProbability is >=0 and <=1&&final.LossProbability is >=0 and <=1,"FinalPrediction W/D/L are out of bounds");Check(Math.Abs(final.WinProbability+final.DrawProbability+final.LossProbability-1.0)<=1e-9,"FinalPrediction W/D/L do not sum to 1");
            Check(final.Simulation.Outcome is not null,"FinalPrediction simulation outcome missing");Check(Math.Abs(final.Simulation.Outcome.WinProbability+final.Simulation.Outcome.DrawProbability+final.Simulation.Outcome.LossProbability-1.0)<=1e-9,"FinalPrediction simulation W/D/L do not sum to 1");Check(final.Simulation.ScoreFrequencies.Count>0,"FinalPrediction simulation score distribution missing");
            var log=MotorRunLogStore.Get("offline-c17-finalprediction");Check(log is not null,"C17 telemetry missing");var m11Index=IndexOf(log!.Stages,x=>x.Motor=="M11"&&x.Status=="completed");Check(m11Index>=0,"M11 completed telemetry missing");Check(log.Stages.Skip(m11Index+1).All(x=>x.Motor!="M9"||x.Status!="completed"),"A second completed M9 stage appeared after M11; final prediction was not a pure continuity handoff");
            Console.WriteLine($"FinalPrediction={final.ExpectedHomeGoals:0.###}-{final.ExpectedAwayGoals:0.###} | W/D/L={final.WinProbability:P1}/{final.DrawProbability:P1}/{final.LossProbability:P1} | simulation={final.Simulation.SimulationCount}");Console.WriteLine("PASS: C17 FinalPrediction continuity");return 0;
        }catch(Exception ex){return Fail("C17 exception: "+ex.Message);}
    }
    private static int IndexOf<T>(IReadOnlyList<T> source,Func<T,bool> predicate){for(var i=0;i<source.Count;i++)if(predicate(source[i]))return i;return -1;}private static Player ReadPlayer(JsonElement e)=>new(e.GetProperty("id").GetInt32(),e.GetProperty("name").GetString()??"Player",e.GetProperty("keeper").GetInt32(),e.GetProperty("defending").GetInt32(),e.GetProperty("playmaking").GetInt32(),e.GetProperty("passing").GetInt32(),e.GetProperty("winger").GetInt32(),e.GetProperty("scoring").GetInt32(),e.GetProperty("stamina").GetInt32(),e.GetProperty("form").GetInt32(),e.GetProperty("experience").GetInt32(),GetInt(e,"loyalty",0),GetInt(e,"injuryLevel",-1));private static RegionalRatingSnapshot ReadRating(JsonElement e){var ld=GetDouble(e,"leftDefence");var cd=GetDouble(e,"centralDefence");var rd=GetDouble(e,"rightDefence");var mid=GetDouble(e,"midfield");var la=GetDouble(e,"leftAttack");var ca=GetDouble(e,"centralAttack");var ra=GetDouble(e,"rightAttack");return new RegionalRatingSnapshot(ld,cd,rd,mid,la,ca,ra,ld,cd,rd,mid,la,ca,ra);}private static string Signature(Lineup lineup)=>string.Join(";",lineup.Slots.OrderBy(s=>s.Code,StringComparer.Ordinal).ThenBy(s=>s.PlayerId).Select(s=>$"{s.Code}:{s.PlayerId}:{(int)s.Order}"));private static string GetString(JsonElement e,string n,string f)=>e.TryGetProperty(n,out var v)&&v.ValueKind==JsonValueKind.String?v.GetString()??f:f;private static int GetInt(JsonElement e,string n,int f)=>e.TryGetProperty(n,out var v)&&v.TryGetInt32(out var x)?x:f;private static double GetDouble(JsonElement e,string n)=>e.GetProperty(n).GetDouble();private static int Fail(string m){Console.WriteLine("FAIL: "+m);return 1;}private static void Check(bool ok,string m){if(!ok)throw new InvalidOperationException(m);}
}
